title: Adele Bass
email: abass@artcenter.edu
assist: Carson Chang
assistemail: carson.chang@icloud.com
description: >-
  Design Fundamentals 2, Expressive Type & Typography 1
baseurl: "/abass"
url: "/abass"
markdown: kramdown
theme: minima
permalink: :categories/:title:output_ext
