---
title: Dr. Sharon Bass, Ph.D
timezone: UTC
collections:
  entries:
    title: Entries
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: drbassisin@gmail.com
description: I see the moment you enter my office as an opening into a more fulfilling
  life. Whatever brings you to therapy, whether the wish to overcome anxiety or depression,  change
  repetitive relationship patterns, unblock creativity, or come to terms with a divorce
  or other seismic shift in circumstances, my hope is to create a trusting relationship
  in which we can work together to explore the inner forces that shape your experience
  and understand what is interfering with your satisfaction in life.
baseurl: 
url: 
markdown: kramdown
